model: yolo26n.pt        
source: dataset/dataset     
data_dir: dataset    

img_size: 640
epochs: 50
batch_size: 128
learn_rate: 1e-4
weight_decay: 1e-4
early_stopping_patience: 5
num_gpus: 2
seed: 42

project: runs/detect
name: bcs
weights: null            

splits:
  train: 0.7
  val: 0.2
  test: 0.1
class_values: [3.25, 3.5, 3.75, 4.0, 4.25]
